Server:
  RunModel: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LoginFileName: app
  LogFileExt: .log

Database:
  DBType: mysql
  Username: root
  Password: rootroot
  Host: 127.0.0.1:3306
  DBName: blog_servic